language: python
python:
  - "2.7"
install:
  - "pip install ImageScraper"
  - "pip install coveralls --use-mirrors"
script: "coverage run --source=image_scraper setup.py test"
after_success: "coveralls"
notifications:
  email: false
